spring:
  application:
    name: user-management-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: p@ssw0rd
  flyway:
    enabled: true
    locations: classpath:db/migration
  session:
    timeout: 60
    redis:
      namespace: spring:session
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      username:
      password: p@ssw0rd
#      lettuce:
#        pool:
#          enabled: true
#          min-idle: 0
#          max-idle: 8
#          max-active: 8


server:
  port: 8080
  servlet:
    context-path: /user-center
